language: php

php: [5.3, 5.4, 5.5]

before_script:
  - export WEB_FIXTURES_HOST=http://localhost
  - export WEB_FIXTURES_BROWSER=firefox
  - export DRIVER_HOST=localhost

  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 4

  - curl http://garr.dl.sourceforge.net/project/sahi/sahi-v44/sahi_20130429.zip > sahi.zip
  - unzip sahi.zip > /dev/null
  - sed -i -e "s,<path>/usr/bin/firefox</path>,<path>/usr/local/bin/firefox</path>,g" sahi/config/browser_types/linux.xml
  - cd sahi/bin
  - sh sahi.sh > /tmp/sahi_output.log &
  - cd -
  - sleep 4

  - composer install --prefer-source

  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 > /dev/null
  - sudo sed -i -e "s,/var/www,$(pwd)/vendor/behat/mink/tests/Behat/Mink/Driver/web-fixtures,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

script: phpunit -v

after_failure:
  - cat /tmp/sahi_output.log